name: Download Lastest Data

on:
  workflow_dispatch:
  push:
  repository_dispatch:
  schedule:
    - cron:  '0 9 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch Latest Data
      run: |-        
        curl https://fonts.google.com/metadata/stats |  sed -e '1,1d' | jq -c . > stats.json
        curl https://fonts.google.com/metadata/fonts | jq -c . > fonts.json
        curl https://fonts.google.com/metadata/icons |  sed -e '1,1d' | jq -c . > icons.json

    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit
        git push
